/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a new user account */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["RegisterRequest"];
        };
      };
      responses: {
        /** @description User registered successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** User login */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["LoginRequest"];
        };
      };
      responses: {
        /** @description Login successful */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** User logout */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Logout successful */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/password-reset": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request password reset */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["PasswordResetRequest"];
        };
      };
      responses: {
        /** @description Password reset email sent */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/password-reset/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Confirm password reset */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["PasswordResetConfirmRequest"];
        };
      };
      responses: {
        /** @description Password reset successful */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid password */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description No token given */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Incorrect token given */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user's profile */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User profile retrieved */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    /** Update current user's profile */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UserUpdateRequest"];
        };
      };
      responses: {
        /** @description User profile updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    /** Delete current user's account */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Email sent to confirm deletion */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me/confirm-deletion": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Confirm deletion of account */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UserDeletionConfirm"];
        };
      };
      responses: {
        /** @description User deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/cars": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user's car information */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of car information */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["CarInfoList"][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Add new car */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CarInfo"];
        };
      };
      responses: {
        /** @description Car information added */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["CarInfo"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/cars/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete a car */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Car deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Car not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    /** Update a car's information */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Car updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Car not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    trace?: never;
  };
  "/parking-spaces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all parking spaces owned by the authenticated user */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of parking spaces grouped by status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              paidSpaces?: components["schemas"]["ParkingSpaceSummary"][];
              freeSpaces?: components["schemas"]["ParkingSpaceSummary"][];
              pendingSpaces?: components["schemas"]["ParkingSpaceSummary"][];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Create a new parking space */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ParkingSpaceCreateRequest"];
        };
      };
      responses: {
        /** @description Parking space created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ParkingSpace"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Search for parking spaces */
    post: {
      parameters: {
        query: {
          latitude: number;
          longitude: number;
          radius?: number;
          available_from?: string;
          available_to?: string;
          paid_status?: "ALL" | "PAID" | "FREE";
          features?: string[];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of parking spaces */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ParkingSpaceSummary"][];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/parking-spaces/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get parking space details */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Parking space details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ParkingSpace"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    /** Delete parking space */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Parking space deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Parking space not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    /** Update parking space */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ParkingSpaceUpdateRequest"];
        };
      };
      responses: {
        /** @description Parking space updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ParkingSpace"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Parking space not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    trace?: never;
  };
  "/reservations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user's reservations */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of reservations */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Reservation"][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Create a new reservation */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ReservationCreateRequest"];
        };
      };
      responses: {
        /** @description Reservation created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Reservation"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reservations/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get reservation details */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Reservation details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Reservation"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    /** Update reservation */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ReservationUpdateRequest"];
        };
      };
      responses: {
        /** @description Reservation updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Reservation"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    /** Cancel reservation */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Reservation canceled */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reservations/lock": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Lock a parking space by Parking Space ID
     * @description Locks a specified parking space for the authenticated user. The user ID is extracted from the authentication token.
     *
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /**
             * Format: uuid
             * @description The unique identifier of the parking space to lock.
             */
            parking_space_id: string;
            /**
             * Format: duration
             * @description Duration for which the parking space should be locked (e.g., "PT15M" for 15 minutes).
             */
            lock_duration: string;
          };
        };
      };
      responses: {
        /** @description Parking space locked successfully. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid input data. */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized. Authentication token is missing or invalid. */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden. User does not have permission to lock this parking space. */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Conflict. Parking space is already locked or reserved. */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reservations/unlock": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Unlock a previously locked parking space
     * @description Unlocks a specified parking space that was previously locked by the authenticated user. The user ID is extracted from the authentication token.
     *
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /**
             * Format: uuid
             * @description The unique identifier of the parking space to unlock.
             */
            parking_space_id: string;
          };
        };
      };
      responses: {
        /** @description Parking space unlocked successfully. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid input data. */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized. Authentication token is missing or invalid. */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden. User does not have permission to unlock this parking space. */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not Found. The parking space is not currently locked by the user. */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/spot-finder/submissions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get user's spot submissions */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of submissions */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SpotFinderSubmission"][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Submit a new spot */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "multipart/form-data": {
            /** Format: binary */
            image?: string;
            /** Format: float */
            latitude?: number;
            /** Format: float */
            longitude?: number;
          };
        };
      };
      responses: {
        /** @description Spot submitted */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SpotFinderSubmission"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/notifications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get user's notifications */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of notifications */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Notification"][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/notifications/{id}/read": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mark notification as read */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Notification marked as read */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get list of users */
    get: {
      parameters: {
        query?: {
          role?: "renter" | "owner" | "spot_finder" | "admin";
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of users */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PublicUserProfile"][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/users/{userId}/suspend": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Suspend a user account */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User suspended */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all reports for the authenticated user */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of user reports */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ReportListResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Create a new report */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ReportCreateRequest"];
        };
      };
      responses: {
        /** @description Report created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Report"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reports/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a specific report by ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Report details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Report"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Report not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    /** Update a report's admin response */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            admin_response: string;
          };
        };
      };
      responses: {
        /** @description Report updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Report"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Report not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    RegisterRequest: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
      full_name: string;
    };
    AuthResponse: {
      access_token?: string;
      name?: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
    };
    PasswordResetRequest: {
      /** Format: email */
      email: string;
    };
    PasswordResetConfirmRequest: {
      token: string;
      /** Format: password */
      new_password: string;
    };
    CarInfo: {
      /** Format: uuid */
      id: string;
      make: string;
      model: string;
      year?: number;
      color?: string;
      license_plate: string;
      license_plate_state: string;
      default?: boolean;
    };
    RenterProfile: {
      car_info?: components["schemas"]["CarInfo"][];
      favorites?: string[];
    };
    Location: {
      /** Format: float */
      latitude: number;
      /** Format: float */
      longitude: number;
      address?: string;
    };
    TimeSlot: {
      /** @enum {string} */
      day_of_week:
        | "Monday"
        | "Tuesday"
        | "Wednesday"
        | "Thursday"
        | "Friday"
        | "Saturday"
        | "Sunday";
      start_time: string;
      end_time: string;
    };
    PricingInfo: {
      /** Format: float */
      base_price: number;
      dynamic_pricing?: boolean;
      dynamic_pricing_algorithm?: string;
    };
    ParkingSpace: {
      /** Format: uuid */
      id: string;
      is_paid: boolean;
      is_taken?: boolean;
      /** Format: uuid */
      owner_id?: string;
      name?: string;
      location: components["schemas"]["Location"];
      features?: string[];
      availability_schedule?: components["schemas"]["TimeSlot"][];
      pricing_info?: components["schemas"]["PricingInfo"];
      photos?: string[];
      /** @enum {string} */
      verification_status?: "verified" | "pending" | "rejected";
      dynamic_pricing_enabled?: boolean;
      cancellation_policy?: string;
      locked?: boolean;
      /** Format: uuid */
      locked_by?: string | null;
      /** Format: date-time */
      locked_until?: string | null;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
      /** @description Average availability rating (1-5). Null if not rated or not a paid spot. */
      avg_availability_rating?: number | null;
      /** @description Average cleanliness rating (1-5). Null if not rated or not a paid spot. */
      avg_cleanliness_rating?: number | null;
      /** @description Average total rating or 'unrated' if no ratings exist. */
      avg_total_rating?: (number | "unrated") | null;
      /** @description Number of users who rated availability. Null if not a paid spot. */
      ratings_count_availability?: number | null;
      /** @description Number of users who rated cleanliness. Null if not a paid spot. */
      ratings_count_cleanliness?: number | null;
    };
    OwnerProfile: {
      parking_spaces?: components["schemas"]["ParkingSpace"][];
      /** Format: float */
      earnings?: number;
    };
    SpotFinderProfile: {
      submissions?: string[];
      points_accumulated?: number;
    };
    NotificationPreferences: {
      email_notifications?: boolean;
      push_notifications?: boolean;
      time?: string;
    };
    UserHomeLocation: {
      state?: string;
      city?: string;
    };
    User: {
      /** Format: uuid */
      id?: string;
      /** Format: email */
      email?: string;
      full_name?: string;
      /** @enum {string} */
      account_status?: "active" | "suspended" | "deleted";
      renter_profile?: components["schemas"]["RenterProfile"];
      owner_profile?: components["schemas"]["OwnerProfile"];
      spot_finder_profile?: components["schemas"]["SpotFinderProfile"];
      notification_preferences?: components["schemas"]["NotificationPreferences"];
      user_location?: components["schemas"]["UserHomeLocation"];
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    UserUpdateRequest: {
      /** Format: email */
      email?: string;
      full_name?: string;
      notification_preferences?: components["schemas"]["NotificationPreferences"];
      notification_time?: string;
    };
    UserDeletionConfirm: {
      token: string;
    };
    CarInfoList: components["schemas"]["CarInfo"][];
    ParkingSpaceSummary: {
      /** Format: uuid */
      id?: string;
      name?: string;
      location?: components["schemas"]["Location"];
      features?: string[];
      /** Format: float */
      average_rating?: number;
      availability?: boolean;
    };
    ParkingSpaceCreateRequest: {
      /** Format: uuid */
      request_id?: string;
      location: components["schemas"]["Location"];
      features: string[];
      availability_schedule: components["schemas"]["TimeSlot"][];
      pricing_info: components["schemas"]["PricingInfo"];
      dynamic_pricing_enabled?: boolean;
      cancellation_policy?: string;
      /** Format: uri */
      proof_of_ownership?: string;
    };
    ParkingSpaceUpdateRequest: {
      /** Format: uuid */
      request_id?: string;
      features?: string[];
      availability_schedule?: components["schemas"]["TimeSlot"][];
      pricing_info?: components["schemas"]["PricingInfo"];
      dynamic_pricing_enabled?: boolean;
      cancellation_policy?: string;
    };
    Reservation: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      parking_space_id: string;
      /** Format: uuid */
      name: string;
      /** Format: uuid */
      renter_id: string;
      /** Format: uuid */
      owner_id: string;
      /** Format: date-time */
      start_time: string;
      /** Format: date-time */
      end_time: string;
      /** @enum {string} */
      status: "booked" | "active" | "completed" | "canceled";
      /** Format: uuid */
      car_info_id: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      price: number;
      location: components["schemas"]["Location"];
    };
    ReservationCreateRequest: {
      /** Format: uuid */
      parking_space_id: string;
      /** Format: date-time */
      start_time: string;
      /** Format: date-time */
      end_time: string;
      /** Format: uuid */
      car_info_id: string;
      /** Format: uuid */
      renter_id: string;
    };
    ReservationUpdateRequest: {
      /** Format: uuid */
      reservation_id: string;
      /** Format: date-time */
      end_time: string;
    };
    SpotFinderSubmission: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      spot_finder_id?: string;
      location?: components["schemas"]["Location"];
      /** Format: uri */
      photo_url?: string;
      /** Format: date-time */
      time?: string;
      /** @enum {string} */
      status?: "verified" | "pending" | "rejected";
      points_awarded?: number;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    Notification: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      user_id?: string;
      type?: string;
      message?: string;
      read?: boolean;
      /** Format: date-time */
      timestamp?: string;
    };
    PublicUserProfile: {
      /** Format: uuid */
      id?: string;
      full_name?: string;
    };
    Report: {
      /**
       * Format: uuid
       * @description Unique identifier for the report.
       */
      id: string;
      /**
       * Format: uuid
       * @description Unique identifier of the user who created the report.
       */
      user_id?: string;
      /**
       * Format: uuid
       * @description Unique identifier of the reservation associated with this report.
       */
      reservation_id?: string | null;
      /**
       * Format: uuid
       * @description Unique identifier of the parking space involved in the reservation.
       */
      parking_space_id?: string | null;
      /** @description Name of the parking space. */
      parking_space_name?: string | null;
      /** @description Address of the parking space. */
      parking_space_address?: string | null;
      /** @description Name of the owner of the parking space. */
      owner_name?: string | null;
      /** @description Name of the renter of the parking space. */
      renter_name?: string | null;
      /**
       * Format: date-time
       * @description Start time of the reservation.
       */
      start_time?: string | null;
      /**
       * Format: date-time
       * @description End time of the reservation.
       */
      end_time?: string | null;
      /**
       * @description Type of the report.
       * @enum {string}
       */
      type: "Reservation Issue" | "Renter Overstay" | "Damage Report" | "Other";
      /** @description Detailed description of the issue. */
      description: string;
      /**
       * @description Current status of the report.
       * @enum {string}
       */
      status: "open" | "in_progress" | "resolved";
      /** @description Response from the admin regarding the report. */
      admin_response?: string | null;
      /**
       * Format: date-time
       * @description Timestamp when the report was created.
       */
      created_at: string;
      /**
       * Format: date-time
       * @description Timestamp when the report was last updated.
       */
      updated_at: string;
      /**
       * Format: date-time
       * @description Actual departure time of the renter (for Renter Overstay reports).
       */
      departure_time?: string | null;
      /** @description Duration of the overstay in minutes (for Renter Overstay reports). */
      overstay_duration?: number | null;
      /** @description Charge for the overstay (for Renter Overstay reports). */
      overstay_charge?: number | null;
      /** @description Type of damage reported (for Damage Report). */
      damage_type?: string | null;
      /** @description Severity of the damage (for Damage Report). */
      damage_severity?: string | null;
      /** @description URL of the image associated with the report. */
      image_url?: string | null;
    };
    ReportListResponse: components["schemas"]["Report"][];
    ReportCreateRequest: {
      /**
       * @description Type of the report.
       * @enum {string}
       */
      type: "Billing" | "Technical" | "Other";
      /** @description Detailed description of the issue. */
      description: string;
      /**
       * Format: date
       * @description Date when the issue occurred.
       */
      date: string;
      /**
       * Format: time
       * @description Time when the issue occurred.
       */
      time: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
