name: Backend Tests
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: python:3-bookworm

    services:
      redis:
        image: redis
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip3 install -r backend/requirements.txt

      - name: mypy
        run: "cd backend && mypy app --strict"

      - name: Check Formatting
        run: "cd backend && black app --check"

      - name: Run Tests
        run: |
          cd backend
          coverage run --source app -m pytest
          coverage report -m --skip-covered --format=markdown > codecov.md

        env:
          TEST_DATABASE_URI: "user=postgres password=postgres host=postgres port=5432"
          DATABASE_URI: "unused"
          TEST_DATABASE_NAME: test_xpark
          REDIS_URI: "redis://redis?db=0"
          SECRET_KEY: test_key

      - name: "Report Code Coverage"
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: backend/codecov.md
        comment_tag: coverage
        mode: recreate
