name: Backend Tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3-bookworm

    services:
      redis:
        image: redis
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # Nix develop + nix cache
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: nicknovitski/nix-develop@972b7cc346f0e0ce0b676231f1544e0bf9323c46

      - name: Check Types
        run: |
          cd backend
          mypy --strict

      - name: Check Formatting
        run: |
          cd backend
          ruff check

      - name: Run Tests
        run: |
          cd backend
          coverage run
          coverage report --format=markdown > codecov.md

        env:
          TEST_DATABASE_URI: "user=postgres password=postgres host=postgres port=5432"
          DATABASE_URI: "unused"
          TEST_DATABASE_NAME: test_xpark
          REDIS_URI: "redis://redis?db=0"
          SECRET_KEY: test_key

      - name: "Report Code Coverage"
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: backend/codecov.md
          comment_tag: coverage
          mode: recreate
