name: Backend Tests
on:
  push:
    branches: ["main"]
    paths: ['backend/**', "flake.nix", "flake.lock", ".github/workflows/backend.yml"]
  pull_request:
    branches: ["main"]
    paths: ['backend/**', "flake.nix", "flake.lock", ".github/workflows/backend.yml"]

defaults:
  run:
    working-directory: backend

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # Nix develop + nix cache
      - uses: DeterminateSystems/nix-installer-action@main
        name: "Install Nix"
      - uses: DeterminateSystems/magic-nix-cache-action@main
        name: "Set up cache"
      - uses: nicknovitski/nix-develop@a2060d116a50b36dfab02280af558e73ab52427d
        name: "Install dependencies"
        with:
          arguments: ".#backend"

      - name: Check Types
        run: |
          mypy --strict

      - name: Check Formatting
        run: |
          ruff check

      - name: Run Tests
        run: |
          coverage run
          coverage report --format=markdown > codecov.md

        env:
          TEST_DATABASE_URI: "user=postgres password=postgres host=127.0.0.1 port=5432"
          DATABASE_URI: "unused"
          TEST_DATABASE_NAME: test_xpark
          SECRET_KEY: test_key
          SENDER_PASSWORD: password

      - name: "Report Code Coverage"
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: backend/codecov.md
          comment_tag: coverage
          mode: recreate
