name: Node.js CI

on:
  push:
    branches: ["main"]
    paths: ['frontend/**', ".github/workflows/node.js.yml"]
  pull_request:
    branches: ["main"]
    paths: ['frontend/**', ".github/workflows/node.js.yml"]

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: '22'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build --if-present
    - name: Test
      run: |
        npm run test:coverage | tail -n +6 | sed '$d' > coverage.md
        sed -i '2,$ s/^/| /; 2,$ s/$/ |/' coverage.md
    - name: "Report Code Coverage"
      if: github.event_name == 'pull_request'
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: frontend/coverage.md
        comment_tag: coverage_frontend
        mode: recreate
